Cleanup execution
dfu-programmer/dfu-programmer pull request #74
Opened 2022-11-25 22:22 UTC by cinderblock

Error first. Makes things easier to extend and understand, imho.

2022-12-13 13:03 UTC, skirridsystems requested changes

2022-12-14 23:17 UTC, cinderblock commented on src/dfu.c
> +        if (tmp > 0) {
Good catch! Fixed

2022-12-14 23:18 UTC, cinderblock commented on src/dfu.c
> +            DEBUG( "Failed to find interface [%d]...\n", tmp );
You're right. `tmp == -1`

2022-12-15 11:08 UTC, skirridsystems approved these changes

2022-12-15 19:27 UTC, merged